version: "3.3"
services:
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        volumes:
            - ../frontend/:/app/result_build/
    db:
        image: postgres:13.0-alpine
        volumes:
            - database:/var/lib/postgresql/data/
        env_file:
            - ./.env
    backend:
        # build: ../backend
        image: dimabaril/foodgram:latest
        restart: always
        volumes:
            - static_value:/app/static/
            - media_value:/app/media/
        env_file:
            - ./.env
        depends_on:
            - db
    nginx:
        image: nginx:1.19.3
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../frontend/build:/usr/share/nginx/html/
            - ../docs/:/usr/share/nginx/html/api/docs/
            - static_value:/var/html/static/
            - media_value:/var/html/media/
        depends_on:
            - backend

volumes:
    static_value:
    media_value:
    database:
