# Generated by Django 4.1.4 on 2022-12-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='ingredientsinrecipe',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
