# Generated by Django 4.1.4 on 2023-01-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_name_alter_tag_color_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Ingredients',
            new_name='Recipe_Ingredient',
        ),
    ]
