# Generated by Django 4.1.4 on 2022-12-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredient_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsInRecipe',
            new_name='Recipe_Ingredients',
        ),
    ]
