# Generated by Django 4.1.4 on 2022-12-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredientsinrecipe_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='quantity',
        ),
    ]
