# Generated by Django 4.1.4 on 2022-12-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_ingredients_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_ingredients',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
