# Generated by Django 4.1.4 on 2023-01-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cooking_time_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Ingredient',
            new_name='RecipeIngredient',
        ),
    ]
