# Generated by Django 4.1.4 on 2022-12-29 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_tags_alter_tag_color_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='recipes.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag')),
            ],
            options={
                'verbose_name': 'Теги в рецепте',
                'verbose_name_plural': 'Теги в рецептах',
            },
        ),
        migrations.DeleteModel(
            name='Recipe_Taaags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='recipes.Recipe_Tags', to='recipes.tag', verbose_name='Тег'),
        ),
    ]
