# Generated by Django 4.1.4 on 2023-01-04 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_rename_recipe_tags_recipe_taaags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredients',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
